<?php
/**
 * SOZO Design
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    SOZO Design
 * @package     Sozo_ProductDownloads
 * @copyright   Copyright (c) 2018 SOZO Design (https://sozodesign.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

$downloads = $block->getDownloads();

if (count($downloads) > 0) :
    ?>
    <div class="product-downloads">

        <strong><?php echo __('Downloads'); ?></strong>

        <ul>
            <div class="download">
                <?php foreach ($downloads as $download) : ?>
                    <li>
                        <a class="c-product__info__item__content--download col-12-12"
                           href="<?php echo $block->getDownloadUrl($download); ?>"
                           target="_blank"><?php echo $download['download_file']; ?></a>
                    </li>
                <?php endforeach; ?>
            </div>
        </ul>

        <div class="clearfix"></div>
    </div>
    <!-- .product-downloads -->
<?php endif; ?>
