<?php
/**
 * SOZO Design
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    SOZO Design
 * @package     Sozo_ProductDownloads
 * @copyright   Copyright (c) 2018 SOZO Design (https://sozodesign.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */

/** @var \Sozo\ProductDownloads\Block\System\Config\Form\Fieldset\Hint $block */
?>
<style>
    #sozo-container {
        background: url('https://sozodesign.co.uk/images/magento/sozo_magento_plugin_about.png') no-repeat scroll 15px #e7efef;
        border: 1px solid #ccc;
        margin: 5px 0;
        padding: 15px 15px 15px 180px;
        min-height: 97px;
    }
</style>
<div id="sozo-container">
    <p>
        <strong>
            SOZO Design Product Downloads Plugin v<?php echo $block->escapeHtml($block->getVersion()) ?>
        </strong> <br>
        Add a download file to your products<br>
    </p>
    <p>
        Website:
        <a href="https://sozodesign.co.uk" target="_blank">sozodesign.co.uk</a><br/>
        Like, share and follow us on
        <a href="https://twitter.com/sozodesign" target="_blank">Twitter</a>,
        <a href="https://plus.google.com/103411336885753828600/" target="_blank">Google+</a>,
        <a href="https://www.youtube.com/user/SozoDesignLtd" target="_blank">YouTube</a>,
        <a href="https://vimeo.com/sozodesign" target="_blank">Vimeo</a>, and
        <a href="http://www.linkedin.com/pub/shaun-uthup/6/785/884" target="_blank">LinkedIn</a>.
    </p>
</div>
